### ISSUE TITLE
Documentation Revamp

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/Documentation#81]
This is a placeholder issue to fix all pending documentation issues and write all pending docs. This would take the documentation project to a stable version `1.0.0`. I'd add (and update accordingly) the tasks required, guidelines, and expectations for this issue below soon; thank you.

## Tasks

- [ ] Review and reorganize the documentation navigation and pages structure.
- [ ] Create tasks for sub-issues.
- [ ] Call for contributors from the OSCA community.
- [ ] Write documentation for pending and new pages
- [ ] Update the contributing guidelines (highlighting the Gitbook integration syncs)
- [ ] Review style guide and templates
- [ ] ...

**Comment by larrymiami** [comment]
@BolajiAyodeji I would like to be part of this, i dont have experience with writing oss documentation but i have been contributing mostly with engineering related issues, if you could point me in the right direction it would gladly help

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji I would like to be part of this, i dont have experience with writing oss documentation but i have been contributing mostly with engineering related issues, if you could point me in the right direction it would gladly help

Sure! We'd be happy to have you help. For now, this project has not commenced and I will communicate when all the tasks for sub-issues are defined (as you might see from the checklist) so you can request to be assigned to any of your choosing. For now, ensure to join our [Discord server](https://discord.gg/pRJgjH9SwR); thank you.

**Comment by victor-cody** [comment]
Hi @BolajiAyodeji I would like to be part of this when the project has commenced. I have experience contributing to OSS documentation and would be absolutely delighted to do that for a project that imparts the African tech community which I am a part of.  😊

**Comment by BolajiAyodeji** [comment]
> Hi @BolajiAyodeji I would like to be part of this when the project has commenced. I have experience contributing to OSS documentation and would be absolutely delighted to do that for a project that imparts the African tech community which I am a part of. 😊

Sure! We'd be happy to have you help.

**Comment by prince0xdev** [comment]
Hello! I am Prince Ekpinse, and I would like to contribute to this issue. Can I take on some of the tasks?
